apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{Deployment}#
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1         
      maxUnavailable: 1 
  selector:
    matchLabels:
      app:   #{Deployment}#
  template:
    metadata:
      labels:
        app:  #{Deployment}#
        type:  #{Deployment}#
    spec:
      containers:
      - name:  #{Deployment}#
        image: iboslimitedbd/#{Deployment}#:#{Build.BuildId}#
        # Environment variable section
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "6Gi"

      imagePullSecrets:
      - name: dockercred

---
apiVersion: v1
kind: Service
metadata:
  name: #{Deployment}#
spec:
  selector:
    app: #{Deployment}#
  ports:
  - port: 80
    # targetPort: 80 
  # type: LoadBalancer
  # loadBalancerIP: 10.17.217.194

  #Ingress SSL with custom path Configurations
